language: python
python:
    - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install pycodestyle pytest-cov
script:
  - pytest --cov=peoplebot --cov=utils --cov-fail-under=39
  - pycodestyle . --max-line-length 120
