name: Run the tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pycodestyle pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pycodestyle
      run: |
        pycodestyle . --max-line-length 120
    - name: Test with pytest
      run: |
        pytest --cov=peoplebot --cov=utils --cov-fail-under=39
  deploy_caprover:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: "${{ secrets.DEPLOY_WEBHOOK_URL }}"
        webhook_secret: "no secret"
